ALTER TABLE dbo.BPK ADD ID INT IDENTITY, KDP3 VARCHAR(11) NULL, TRXSTATUS INT NOT NULL DEFAULT 0
GO

ALTER TABLE dbo.BPK DROP CONSTRAINT PK_BPK
GO

ALTER TABLE dbo.BPK
ADD CONSTRAINT PK_BPK
    PRIMARY KEY NONCLUSTERED (
                                 ID ASC,
                                 UNITKEY ASC,
                                 NOBPK ASC
                             )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
          ALLOW_PAGE_LOCKS = ON
         ) ON [PRIMARY]
GO

ALTER TABLE dbo.BPK
ADD CONSTRAINT UC_BPK UNIQUE(NOBPK, UNITKEY)
GO

ALTER TABLE dbo.BPK
ADD FOREIGN KEY(KDP3) REFERENCES dbo.DAFTPHK3(KDP3)
GO