ALTER TABLE dbo.PGRMUNIT ADD ID INT IDENTITY
GO

ALTER TABLE dbo.PGRMUNIT DROP CONSTRAINT PK_PGRMUNIT
GO

ALTER TABLE dbo.PGRMUNIT
ADD CONSTRAINT PK_PGRMUNIT
    PRIMARY KEY NONCLUSTERED (
                                 [ID] ASC,
								 KDTAHAP ASC,
								 UNITKEY ASC,
								 IDPRGRM ASC
                             )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
          ALLOW_PAGE_LOCKS = ON
         ) ON [PRIMARY]
GO

ALTER TABLE dbo.PGRMUNIT
ADD CONSTRAINT UC_PGRMUNIT UNIQUE(KDTAHAP, UNITKEY, IDPRGRM)
GO