ALTER TABLE dbo.BKPAJAK ADD ID INT IDENTITY
GO

ALTER TABLE dbo.BKPAJAK DROP CONSTRAINT PK_BKPAJAK
GO

ALTER TABLE dbo.BKPAJAK
ADD CONSTRAINT PK_BKPAJAK
    PRIMARY KEY NONCLUSTERED (
                                 [ID] ASC,
                                 [UNITKEY] ASC,
                                 [NOBKPAJAK] ASC
                             )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
          ALLOW_PAGE_LOCKS = ON
         ) ON [PRIMARY]
GO

ALTER TABLE dbo.BKPAJAK
ADD CONSTRAINT UC_BKPAJAK UNIQUE(UNITKEY, NOBKPAJAK)
GO