ALTER TABLE dbo.BKPAJAKDET ADD ID INT IDENTITY, KDBILLING NVARCHAR(255) NULL, NTPN NVARCHAR(255) NULL
GO

ALTER TABLE dbo.BKPAJAKDET DROP CONSTRAINT PK_BKPAJAKDET
GO

ALTER TABLE dbo.BKPAJAKDET
ADD CONSTRAINT PK_BKPAJAKDET
    PRIMARY KEY NONCLUSTERED (
                                 [ID] ASC,
                                 [UNITKEY] ASC,
                                 [NOBKPAJAK] ASC,
                                 [PJKKEY] ASC
                             )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
          ALLOW_PAGE_LOCKS = ON
         ) ON [PRIMARY]
GO

ALTER TABLE dbo.BKPAJAKDET 
ADD CONSTRAINT UC_BKPAJAKDET UNIQUE(UNITKEY, NOBKPAJAK, PJKKEY)
GO

ALTER TABLE dbo.BKPAJAKDET
ADD TRXSTATUS INT NOT NULL DEFAULT 0 
GO