--USE [V@LID49V6_2019]
--GO

/****** Object:  StoredProcedure [dbo].[CMS_CREATE_TRXSPJ_POT]    Script Date: 20/02/2020 01:16:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[CMS_CREATE_TRXSPJ_POT]
(@UnitKey NVARCHAR(255), @NoBPK NVARCHAR(255))
AS
BEGIN
DECLARE @Tahun INT, @NoPungut NVARCHAR(255), @NoSetor NVARCHAR(255)
SET @Tahun=(SELECT TOP(1)CAST(p.CONFIGVAL AS INT)
            FROM dbo.PEMDA p
            WHERE p.CONFIGID='cur_thang '
            ORDER BY p.CONFIGID);

SET @NoPungut = (SELECT TOP(1) b.NOBKPAJAK FROM dbo.BPKPAJAK b WHERE b.NOBPK = @NoBPK AND b.UNITKEY = @UnitKey ORDER BY b.NOBPK)

SET @NoSetor = (SELECT TOP(1) p.NOSETOR FROM dbo.PJKPS p WHERE p.NOPUNGUT = @NoPungut ORDER BY p.NOSETOR)

SELECT 
@Tahun AS Tahun,
b.NOBKPAJAK AS No_Bukti,
CAST(b2.KDSTATUS AS INT) AS Jns_Dok,
SUBSTRING(j2.kodeAkunPajak, 1, 1) AS Kd_Rek_1,
SUBSTRING(j2.kodeAkunPajak, 2, 1) AS Kd_Rek_2,
SUBSTRING(j2.kodeAkunPajak, 3, 1) AS Kd_Rek_3,
SUBSTRING(j2.kodeAkunPajak, 4, 1) AS Kd_Rek_4,
SUBSTRING(j2.kodeAkunPajak, 5, 1) AS Kd_Rek_5,
j2.namaAkunPajak AS Nm_Rekening,
b.NILAI AS Nilai,
b.KDBILLING AS Kd_Billing,
b.ID AS RefId
FROM dbo.BKPAJAKDET b 
INNER JOIN dbo.BKPAJAK b2
ON b2.NOBKPAJAK = b.NOBKPAJAK AND b2.UNITKEY = b.UNITKEY
INNER JOIN dbo.JPAJAK j
ON j.PJKKEY = b.PJKKEY
INNER JOIN dbo.JPAJAKKEU j2
ON j2.KDPAJAK = j.KDPAJAK
WHERE b.NOBKPAJAK = @NoSetor AND b.UNITKEY = @UnitKey
END
GO


