--Patch DB SIPKD

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='JPAJAKKEU')
Drop TABLE JPAJAKKEU

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MATANGBKEU')
Drop TABLE MATANGBKEU

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MATANGBKEU')
SELECT *,KDPER AS kodeAkunPajak,NMPER AS namaAkunPajak INTO MATANGBKEU FROM MATANGB WHERE KDPER LIKE '7.%' AND MTGLEVEL='3'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='JPAJAKKEU')
SELECT *,KDPAJAK AS kodeAkunPajak,NMPAJAK AS namaAkunPajak INTO JPAJAKKEU FROM JPAJAK where lower(KDPAJAK) like 'ppn%' OR lower(KDPAJAK) like 'pph%'
OR lower(KDPAJAK) like 'iwp%' OR lower(KDPAJAK) like 'taperum%' or lower(KDPAJAK) like 'taspen%' OR lower(KDPAJAK) like 'askes%'
or lower(KDPAJAK) like 'bpjs%' OR lower(KDPAJAK) like 'lain%'

UPDATE JPAJAKKEU SET kodeAkunPajak='411121' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%21%') OR (LOWER(NMPAJAK) LIKE '%21%')
UPDATE JPAJAKKEU SET kodeAkunPajak='411122' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%22%') OR (LOWER(NMPAJAK) LIKE '%22%')
UPDATE JPAJAKKEU SET kodeAkunPajak='411124' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%23%') OR (LOWER(NMPAJAK) LIKE '%23%')
UPDATE JPAJAKKEU SET kodeAkunPajak='411126' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%25%') OR (LOWER(NMPAJAK) LIKE '%25%')
UPDATE JPAJAKKEU SET kodeAkunPajak='411127' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%26%') OR (LOWER(NMPAJAK) LIKE '%26%')
UPDATE JPAJAKKEU SET kodeAkunPajak='411128' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%4%') OR (LOWER(NMPAJAK) LIKE '%4%')
UPDATE JPAJAKKEU SET kodeAkunPajak='411128' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%15%') OR (LOWER(NMPAJAK) LIKE '%15%')
UPDATE JPAJAKKEU SET kodeAkunPajak='411211' WHERE LOWER(KDPAJAK) LIKE 'ppn%'  
UPDATE JPAJAKKEU SET kodeAkunPajak='100001' WHERE LOWER(KDPAJAK) LIKE '%iwp%' OR (LOWER(NMPAJAK) LIKE '%Iuran Wajib Pegawai%')  
UPDATE JPAJAKKEU SET kodeAkunPajak='100002' WHERE LOWER(KDPAJAK) LIKE '%taperum%' OR (LOWER(NMPAJAK) LIKE '%taperum%')  OR (LOWER(NMPAJAK) LIKE '%tabungan perumahan%')  
UPDATE JPAJAKKEU SET kodeAkunPajak='100003' WHERE LOWER(KDPAJAK) LIKE '%taspen%' OR (LOWER(NMPAJAK) LIKE '%taspen%')  OR (LOWER(NMPAJAK) LIKE '%tabungan pensiun%')  
UPDATE JPAJAKKEU SET kodeAkunPajak='100004' WHERE LOWER(KDPAJAK) LIKE '%askes%' OR (LOWER(NMPAJAK) LIKE '%askes%') OR (LOWER(NMPAJAK) LIKE '%bpjs%')  
UPDATE JPAJAKKEU SET kodeAkunPajak='100005' WHERE LOWER(NMPAJAK) LIKE '%Lain%' 


UPDATE JPAJAKKEU SET namaAkunPajak='Pajak Penghasilan Ps 21' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%21%') OR (LOWER(NMPAJAK) LIKE '%21%')
UPDATE JPAJAKKEU SET namaAkunPajak='Pajak Penghasilan Ps 22' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%22%') OR (LOWER(NMPAJAK) LIKE '%22%')
UPDATE JPAJAKKEU SET namaAkunPajak='Pajak Penghasilan Ps 23' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%23%') OR (LOWER(NMPAJAK) LIKE '%23%')
UPDATE JPAJAKKEU SET namaAkunPajak='Pajak Penghasilan Ps 25' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%25%') OR (LOWER(NMPAJAK) LIKE '%25%')
UPDATE JPAJAKKEU SET namaAkunPajak='Pajak Penghasilan Ps 26' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%26%') OR (LOWER(NMPAJAK) LIKE '%26%')
UPDATE JPAJAKKEU SET namaAkunPajak='Pajak Penghasilan Ps 4 (2)' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%4%') OR (LOWER(NMPAJAK) LIKE '%4%')
UPDATE JPAJAKKEU SET namaAkunPajak='Pajak Penghasilan Ps 15' WHERE (LOWER(KDPAJAK) LIKE 'pph%' and LOWER(KDPAJAK) LIKE '%15%') OR (LOWER(NMPAJAK) LIKE '%15%')
UPDATE JPAJAKKEU SET namaAkunPajak='Pajak Pertambahan Nilai (PPN)' WHERE (LOWER(KDPAJAK) LIKE 'ppn%') 




UPDATE MATANGBKEU SET kodeAkunPajak='411121' WHERE (LOWER(NMPER) LIKE '%pph%' OR LOWER(NMPER) LIKE '%21%') OR (LOWER(NMPER) LIKE '%21%')
UPDATE MATANGBKEU SET kodeAkunPajak='411122' WHERE (LOWER(NMPER) LIKE '%pph%' and LOWER(NMPER) LIKE '%22%') OR (LOWER(NMPER) LIKE '%22%')
UPDATE MATANGBKEU SET kodeAkunPajak='411124' WHERE (LOWER(NMPER) LIKE '%pph%' and LOWER(NMPER) LIKE '%23%') OR (LOWER(NMPER) LIKE '%23%')
UPDATE MATANGBKEU SET kodeAkunPajak='411126' WHERE (LOWER(NMPER) LIKE '%pph%' and LOWER(NMPER) LIKE '%25%') OR (LOWER(NMPER) LIKE '%25%')
UPDATE MATANGBKEU SET kodeAkunPajak='411127' WHERE (LOWER(NMPER) LIKE '%pph%' and LOWER(NMPER) LIKE '%26%') OR (LOWER(NMPER) LIKE '%26%')
UPDATE MATANGBKEU SET kodeAkunPajak='411128' WHERE (LOWER(NMPER) LIKE '%pph%' and LOWER(NMPER) LIKE '%4%') OR (LOWER(NMPER) LIKE '%4%')
UPDATE MATANGBKEU SET kodeAkunPajak='411128' WHERE (LOWER(NMPER) LIKE '%pph%' and LOWER(NMPER) LIKE '%15%') OR (LOWER(NMPER) LIKE '%15%')
UPDATE MATANGBKEU SET kodeAkunPajak='411211' WHERE LOWER(NMPER) LIKE '%ppn%'  
UPDATE MATANGBKEU SET kodeAkunPajak='100001' WHERE (LOWER(NMPER) LIKE '%IWP%') OR (LOWER(NMPER) LIKE '%Iuran Wajib Pegawai%')  
UPDATE MATANGBKEU SET kodeAkunPajak='100002' WHERE (LOWER(NMPER) LIKE '%taperum%')  OR (LOWER(NMPER) LIKE '%tabungan perumahan%')  
UPDATE MATANGBKEU SET kodeAkunPajak='100003' WHERE (LOWER(NMPER) LIKE '%taspen%')  OR (LOWER(NMPER) LIKE '%tabungan pensiun%')  
UPDATE MATANGBKEU SET kodeAkunPajak='100004' WHERE (LOWER(NMPER) LIKE '%askes%') OR (LOWER(NMPER) LIKE '%bpjs%') OR (LOWER(NMPER) LIKE '%asuransi kesehatan%')
UPDATE MATANGBKEU SET kodeAkunPajak='100005' WHERE LOWER(NMPER) LIKE '%Lain%' 
UPDATE MATANGBKEU SET kodeAkunPajak='0' WHERE 
LOWER(NMPER) not LIKE '%pph%' AND LOWER(NMPER) not LIKE '%ppn%' AND
((LOWER(NMPER) not LIKE '%IWP%') AND (LOWER(NMPER) not LIKE '%Iuran Wajib Pegawai%'))  AND
((LOWER(NMPER) not LIKE '%taperum%')  AND (LOWER(NMPER) not LIKE '%tabungan perumahan%'))AND  
((LOWER(NMPER) not LIKE '%taspen%')  AND (LOWER(NMPER) not LIKE '%tabungan pensiun%'))  AND
((LOWER(NMPER) not LIKE '%askes%') AND (LOWER(NMPER) not LIKE '%bpjs%') AND (LOWER(NMPER) not LIKE '%asuransi kesehatan%'))AND
(LOWER(NMPER) not LIKE '%Lain%' )

UPDATE MATANGBKEU SET namaAkunPajak='IWP' WHERE (LOWER(KDPER) LIKE '%iwp%') OR (LOWER(NMPER) LIKE '%Iuran Wajib Pegawai%')
UPDATE MATANGBKEU SET namaAkunPajak='Taperum' WHERE (LOWER(KDPER) LIKE '%taperum%') OR (LOWER(NMPER) LIKE '%tabungan perumahan%')
UPDATE MATANGBKEU SET namaAkunPajak='Taspen' WHERE LOWER(KDPER) LIKE '%taspen%' OR (LOWER(NMPER) LIKE '%tabungan pensiun%')
UPDATE MATANGBKEU SET namaAkunPajak='Askes/BPJS' WHERE LOWER(KDPER) LIKE '%askes%' OR (LOWER(NMPER) LIKE '%askes%') OR (LOWER(NMPER) LIKE '%bpjs%')OR (LOWER(NMPER) LIKE '%asuransi kesehatan%')
UPDATE MATANGBKEU SET namaAkunPajak='Lain-lain' WHERE LOWER(NMPER) LIKE '%Lain%'

select * from JPAJAKKEU where len(kodeAkunPajak) > 0 
select * from MATANGBKEU where len(kodeAkunPajak) > 0 
