--USE [V@LID49V6_2019]
GO

/****** Object:  Table [dbo].[REKPENAMPUNG]    Script Date: 13/03/2020 00:24:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[REKPENAMPUNG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KDBANK] [dbo].[KODEC2] NOT NULL,
	[ACCOUNTNO] [nvarchar](50) NOT NULL,
	[ACCOUNTNAME] [nvarchar](255) NULL,
	[ACCOUNTDESC] [nvarchar](255) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[REKPENAMPUNG]  WITH CHECK ADD  CONSTRAINT [FK_REKPENAMPUNG_DAFTBANK] FOREIGN KEY([KDBANK])
REFERENCES [dbo].[DAFTBANK] ([KDBANK])
GO

ALTER TABLE [dbo].[REKPENAMPUNG] CHECK CONSTRAINT [FK_REKPENAMPUNG_DAFTBANK]
GO


