USE [V@LID49V6_2020_CMS]
GO

/****** Object:  StoredProcedure [dbo].[CMS_CREATE_TRXSPJ]    Script Date: 07/10/2020 01:14:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[CMS_CREATE_TRXSPJ]
(@UnitKey NVARCHAR(255), @NoBPK NVARCHAR(255))
AS
BEGIN
--DECLARE @UnitKey NVARCHAR(255), @NoBPK NVARCHAR(255);
--SET @UnitKey=N'85_';
--SET @NoBPK=N'01843/BPK/UP/6.00.01.01./B02/2019';
DECLARE @Tahun INT;
SET @Tahun=(SELECT TOP(1)CAST(p.CONFIGVAL AS INT)
            FROM dbo.PEMDA p
            WHERE p.CONFIGID='cur_thang '
            ORDER BY p.CONFIGID);
SELECT @Tahun AS Tahun, RTRIM(b.NOBPK) AS No_Bukti, 21 AS Jns_Dok, LEFT(d.KDUNIT, 1) Kd_Urusan, 
CAST(CAST((SUBSTRING(d.KDUNIT, 3, 2)) AS INT) AS CHAR(2)) Kd_Bidang, 
CAST(CAST((SUBSTRING(d.KDUNIT, 6, 2)) AS INT) AS CHAR(2)) Kd_Unit, 
CAST(CAST((SUBSTRING(d.KDUNIT, 9, 2)) AS INT) AS CHAR(2)) Kd_Sub, 
b.TGLBPK AS Tgl_Bukti, d2.NMP3 AS Nm_Penerima, d3.NMBANK AS Bank_Penerima, 
d2.NORCP3 AS Rek_Penerima, df.NMBANK AS Nm_Bank, d2.NPWP, 
b.URAIBPK AS Keterangan, REPLACE(bend.REKBEND, '.', '') AS No_Rekening, 
SUM(b3.NILAI) AS Nilai, GETDATE() AS DateCreate, 0 AS Cair, NULL AS TglCair,
d.NMUNIT AS Nm_Unit, d.NMUNIT AS Nm_Sub_Unit, '' AS Uraian, b.ID AS RefId
FROM dbo.BPK b
	 INNER JOIN dbo.BEND bend ON bend.KEYBEND = b.KEYBEND AND bend.UNITKEY = b.UNITKEY
	 INNER JOIN DAFTBANK df ON df.KDBANK = bend.KDBANK
     INNER JOIN dbo.DAFTUNIT d ON d.UNITKEY=b.UNITKEY
     INNER JOIN dbo.DAFTPHK3 d2 ON d2.KDP3=b.KDP3
     INNER JOIN dbo.DAFTBANK d3 ON d2.KDBANK=d3.KDBANK
     INNER JOIN dbo.BPKDETR b3 ON b3.NOBPK=b.NOBPK AND b3.UNITKEY=b.UNITKEY
WHERE b.UNITKEY=@UnitKey AND b.NOBPK=@NoBPK
GROUP BY b.KDSTATUS, b.NOBPK, d.KDUNIT, b.TGLBPK, d2.NMP3, df.NMBANK, bend.REKBEND, d3.NMBANK, d2.NORCP3, d2.NPWP, b.URAIBPK, d.NMUNIT, b.ID;
END

GO

